name: Build
on: [push, workflow_dispatch] # 手動(workflow_dispatch)でも動かせるようにします
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # 128エラー（ submoduleの読み込み失敗）を防ぎます

      - name: Install west
        run: pip3 install west

      - name: West init
        run: west init -l config

      - name: West update
        run: west update

      - name: West build
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=totem_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          mv build/zephyr/zmk.uf2 totem_left.uf2
          west build -p -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=totem_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          mv build/zephyr/zmk.uf2 totem_right.uf2

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: totem_firmware
          path: "*.uf2"
